### ISSUE TITLE
Log in screen doesn't allow for Command (⌘) + [trigger key] options

### ISSUE THREAD

**Issue by alextechtai** [vitorgalvao/fog#13] opened 2019-06-07 09:32 UTC
I'm having trouble pasting (Command (⌘) + V), or highlighting Command (⌘) + A

**Comment by vitorgalvao** [comment] 2019-06-07 13:56
Thank you for the bug report, but you’ve given me no information with which to debug it.

Think about it: if you only post “I have this error”, what more can I say than “I don’t” and close the issue?

What’s your macOS version? What’s your Fog version? Where have you downloaded it from? Were you using it successfully before and it started erroring out, or is it your first launch? Are you running the packaged app, or trying to develop on it? I need details to be able to help you.

**Comment by alextechtai** [comment] 2019-06-08 19:13
@vitorgalvao So sorry about that! I just freshly installed it and did not run it before. Now that you've mentioned it, the copy and paste problem only happens the first time launching the app. I just tried logging out and logging back into Overcast and I could do copy and pasting now. But when I am filling out the credentials, the cursor doesn't show.

- macOS 10.15
- Fog Version 1.4.5 (1.4.5)
- downloaded via Homebrew

**Comment by vitorgalvao** [comment] 2019-06-08 19:29
10.15 is still a beta, and from [what I’ve heard](https://atp.fm/episodes/329) Apple engineers recommend people don’t install beta 1.

Seeing as:

* I don’t have a way to test this on macOS Catalina.
* Catalina is a beta OS, meaning it’s likely any bug appearing in apps will either:
  * Be solved by Apple.
  * Be solved by Github (Electron).
* The app is distributed for free, but it’s not free for me to give it away and support it.
* I can’t reproduce (because I’m not on that system).
* There is a chance I’ll deprecate this once Marco Arment (Overcast’s creator) releases an official macOS app (he’s working on it right now, via Project Catalyst).

I’m closing. I may revisit this at a later point (closer to the release of Catalina), but right now looking for bugs caused by the OS for an app that consumes time and doesn’t create revenue is like punching oneself in the face (which I don’t enjoy).

Thank you for the bug report anyway.

**Closed as completed by vitorgalvao** 2019-06-08 19:29 UTC

**Comment by qwinters** [comment] 2020-09-28 14:59
@vitorgalvao Can you revisit this?

**Comment by vitorgalvao** [comment] 2020-09-29 11:17
> @vitorgalvao Can you revisit this?

Nothing has changed from the previous answer. I’m still not on Catalina and working on this still costs me time (and money) which I now have less of.

I’ll take a PR (small incremental ones) to fix any problems, but otherwise don’t plan to look into it for the foreseeable future unless I’m paid for that time.

The good news is that the problem can probably be fixed by updating the dependencies (specifically Electron), but the bad news is that they change the API so often it’s likely other changes will be needed as well.
