### ISSUE TITLE
App background is grey on macOS High Sierra

### ISSUE THREAD

**Issue by keirwilliams-old** [vitorgalvao/fog#4] opened 2017-09-18 14:10 UTC
<img width="334" alt="screen shot 2017-09-18 at 15 09 48" src="https://user-images.githubusercontent.com/26045249/30546065-7463bb04-9c83-11e7-9566-485e27d2843b.png">

**Comment by vitorgalvao** [comment] 2017-09-18 17:11
Try the latest version (`1.2.1`). If it still persists, it’s likely something on Electron’s side and I’ll only be able to test after I upgrade to High Sierra.

Please report back if the new version fixes it.

**Comment by keirwilliams-old** [comment] 2017-09-18 18:18
It's the same still.

**Comment by vitorgalvao** [comment] 2017-09-18 18:31
Then there is a chance this is something that needs to be fixed on Electron’s side. I should upgrade to High Sierra in the weeks after it comes out, so I’ll take a look then.

If anyone finds the cause and provides a fix in the meantime, I can merge that.

**Comment by joevo2** [comment] 2017-09-27 02:52
Having the same issue as well

**Comment by vitorgalvao** [comment] 2017-09-29 17:14
Should be fixed in `1.3.0`.

**Closed as completed by vitorgalvao** 2017-09-29 17:14 UTC
